title: Lukáš Lalinský
email: lukas@lalinsky.com
url: https://lalinsky.com
repository: lalinsky/lalinsky.com
remote_theme: "mmistakes/so-simple-theme@3.2.0"

date_format: "%Y-%m-%d"
read_time: false
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

permalink: /:year/:month/:day/:title:output_ext

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: /page:num/

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

author:
  name: Lukáš Lalinský
  email: lukas@lalinsky.com

footer_links:
  - title: Email
    url: mailto:lukas@lalinsky.com
    icon: fas fa-envelope-square
  - title: GitHub
    url: https://github.com/lalinsky
    icon: fab fa-github-square
  - title: Bluesky
    url: https://bsky.app/profile/lukaslalinsky.bsky.social
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/lalinsky
    icon: fab fa-linkedin
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
